### ISSUE TITLE
KernelSU says not installed click to install what to do next

### ISSUE THREAD

**Issue by N30Z3N** [g8row/gphotos-guide#1]
![Screenshot (118)](https://github.com/g8row/gphotos-guide/assets/54675598/7ae7b822-eba4-4a9a-ad73-f7af3139077b)

**Comment by g8row** [comment]
can you tell me exactly which version of wsa did you install? For example `WSA_XXXX.X0000.X.0_XXXX_Release-Nightly-kernelsu-vX.X.X-MindTheGapps-XX.X-RemovedAmazon.7z`. Are you sure the file name contains `kernel-su`? This is detailed in [Step 0](https://github.com/g8row/gphotos-guide#step-0)

**Comment by N30Z3N** [comment]
> can you tell me exactly which version of wsa did you install? For example `WSA_XXXX.X0000.X.0_XXXX_Release-Nightly-kernelsu-vX.X.X-MindTheGapps-XX.X-RemovedAmazon.7z`. Are you sure the file name contains `kernel-su`? This is detailed in [Step 0](https://github.com/g8row/gphotos-guide#step-0)

I had previously installed WSA so removed it for clean install but after extracting file I got some 26 broken files in 
https://github.com/MustardChef/WSABuilds/releases/download/Windows_11_2311.40000.5.0_arm64/WSA_2311.40000.5.0_arm64_Release-Nightly-with-KernelSU-v0.7.5-MindTheGapps-13.0-RemovedAmazon.7z  

what should I do go for another release ?

**Comment by g8row** [comment]
> > can you tell me exactly which version of wsa did you install? For example `WSA_XXXX.X0000.X.0_XXXX_Release-Nightly-kernelsu-vX.X.X-MindTheGapps-XX.X-RemovedAmazon.7z`. Are you sure the file name contains `kernel-su`? This is detailed in [Step 0](https://github.com/g8row/gphotos-guide#step-0)
> 
> I had previously installed WSA so removed it for clean install but after extracting file I got some 26 broken files in https://github.com/MustardChef/WSABuilds/releases/download/Windows_11_2311.40000.5.0_arm64/WSA_2311.40000.5.0_arm64_Release-Nightly-with-KernelSU-v0.7.5-MindTheGapps-13.0-RemovedAmazon.7z
> 
> what should I do go for another release ?

i'm not the dev of wsa-builds so you should ask there instead.

try to update your 7zip install if you have problems with extraction. kernelsu is built into the kernel so it shouldn't be missing.
