### ISSUE TITLE
Please release the VM version so we can download and start it directly in the VM.

### ISSUE THREAD

**Issue by 088** [g8row/gphotos-guide#2]
Please release the VM version so we can download and start it directly in the VM.

Thank you.

**Comment by g8row** [comment]
I don't understand what you mean.

**Comment by 088** [comment]
What I mean is: you can use VMware to install Windows 10 and complete Step 0 to Step 7, then export the virtual machine, for example, as an .ovf file, and finally make these .ovf files available for us to download. This way, we can use it directly, but it's too much trouble. Thank you.

**Comment by 088** [comment]
I successfully uploaded the photos to Google Photos following your steps. Thank you.  Great Project!!!
