### ISSUE TITLE
Syncthing is not available

### ISSUE THREAD

**Issue by hadikamel** [g8row/gphotos-guide#3]
Hi and Thanks
The app that is said in last step, [Syncthing](https://play.google.com/store/apps/details?id=com.nutomic.syncthingandroid&hl=en&gl=US)  is not available in Google store and what is it alternative?

Best Regards

**Comment by g8row** [comment]
Syncthing seems to have an issue with the Play Store currently, as per this [issue](https://github.com/syncthing/syncthing-android/issues/2064). You can still grab it from [Github Releases](https://github.com/syncthing/syncthing-android/releases) on the Syncthing repo and [F-Droid](https://f-droid.org/packages/com.nutomic.syncthingandroid/).

**Comment by hadikamel** [comment]
> Syncthing seems to have an issue with the Play Store currently, as per this [issue](https://github.com/syncthing/syncthing-android/issues/2064). You can still grab it from [Github Releases](https://github.com/syncthing/syncthing-android/releases) on the Syncthing repo and [F-Droid](https://f-droid.org/packages/com.nutomic.syncthingandroid/).

Merc
