### ISSUE TITLE
Cannot sign into Google Play

### ISSUE THREAD

**Issue by misterpyrrhuloxia** [g8row/gphotos-guide#5]
I followed the instructions to install the `WSA_XXXX.X0000.X.0_XXXX_Release-Nightly-kernelsu-vX.X.X-MindTheGapps-XX.X-RemovedAmazon.7z` which worked fine. I then launch the Google Play Store, hit Sign In, and get this an error that says, "Something went wrong... please go back and try again".

Can someone please help me figure out why this keeps happening?

**Comment by g8row** [comment]
this is not an issue related to my guide, you can ask on the WSABuilds [repo](https://github.com/MustardChef/WSABuilds) or discord for help.
